# ABOUTME: Formats a DiffResult as a Markdown string for PR comments.
# ABOUTME: Also formats per-endpoint AI prompts for clipboard copy.

from apilens.models import DiffResult, FieldStatus, ModifiedEndpoint

_METHOD_ICONS = {
    "GET": "🔵",
    "POST": "🟢",
    "PUT": "🟠",
    "PATCH": "🟡",
    "DELETE": "🔴",
}


def _icon(method: str) -> str:
    return _METHOD_ICONS.get(method.upper(), "⚪")


def as_pr_comment(diff: DiffResult, base_label: str, head_label: str) -> str:
    total = (
        len(diff.new_endpoints)
        + len(diff.missing_endpoints)
        + len(diff.modified_endpoints)
    )

    if total == 0:
        return (
            "## ApiLens — API Diff\n\n"
            f"No API changes between `{base_label}` and `{head_label}`."
        )

    lines = [
        "## ApiLens — API Diff",
        "",
        f"Comparing `{base_label}` → `{head_label}`",
        "",
    ]

    if diff.new_endpoints:
        lines.append(f"### ➕ New Endpoints ({len(diff.new_endpoints)})")
        lines.append("")
        for ep in diff.new_endpoints:
            lines.append(f"- {_icon(ep.method)} `{ep.method} {ep.path}`")
        lines.append("")

    if diff.missing_endpoints:
        lines.append(f"### ➖ Removed Endpoints ({len(diff.missing_endpoints)})")
        lines.append("")
        for ep in diff.missing_endpoints:
            lines.append(f"- {_icon(ep.method)} `{ep.method} {ep.path}`")
        lines.append("")

    if diff.modified_endpoints:
        lines.append(f"### ✏️ Modified Endpoints ({len(diff.modified_endpoints)})")
        lines.append("")
        for ep in diff.modified_endpoints:
            lines.append(
                f"<details><summary>{_icon(ep.method)} "
                f"<code>{ep.method} {ep.path}</code></summary>"
            )
            lines.append("")
            for change in ep.changes:
                lines.append(f"**{change.location}**")
                lines.append("")
                lines.append("| Field | Change |")
                lines.append("| ----- | ------ |")
                for field in change.fields:
                    if field.status == FieldStatus.added:
                        lines.append(f"| `{field.name}` | ➕ added |")
                    elif field.status == FieldStatus.removed:
                        lines.append(f"| `{field.name}` | ➖ removed |")
                lines.append("")
            lines.append("</details>")
            lines.append("")

    lines.append("---")
    lines.append("*Generated by [ApiLens](https://github.com/your-org/api-lens)*")
    return "\n".join(lines)


def as_ai_prompt(diff: DiffResult) -> str:
    lines = [
        "The backend API has changed. Update TypeScript types and data-fetching code accordingly.",
        "",
    ]
    if diff.new_endpoints:
        lines.append("## New Endpoints")
        for ep in diff.new_endpoints:
            lines.append(f"  + {ep.method} {ep.path}")
        lines.append("")

    if diff.missing_endpoints:
        lines.append("## Removed Endpoints")
        for ep in diff.missing_endpoints:
            lines.append(f"  - {ep.method} {ep.path}")
        lines.append("")

    if diff.modified_endpoints:
        lines.append("## Modified Endpoints")
        for ep in diff.modified_endpoints:
            for change in ep.changes:
                lines.append("")
                lines.append(f"  {ep.method} {ep.path} ({change.location})")
                for field in change.fields:
                    if field.status != FieldStatus.unchanged:
                        sym = "+ " if field.status == FieldStatus.added else "- "
                        lines.append(f"    {sym}{field.name}")
        lines.append("")

    lines.append("---")
    if diff.new_endpoints:
        lines.append(
            "For new endpoints: add TypeScript types and implement client-side fetching."
        )
    if diff.missing_endpoints:
        lines.append(
            "For removed endpoints: remove or update all code that calls them."
        )
    if diff.modified_endpoints:
        lines.append(
            "For modified endpoints: update the TypeScript response type and any component or hook that reads from it."
        )
    return "\n".join(lines)


def as_endpoint_ai_prompt(ep: ModifiedEndpoint) -> str:
    lines = [
        "The following API endpoint response has changed.",
        "Update the TypeScript type and any component or hook that calls it.",
        "",
        f"{ep.method} {ep.path}",
        "",
    ]
    for change in ep.changes:
        lines.append(f"{change.location}:")
        for field in change.fields:
            sym = (
                "+ "
                if field.status == FieldStatus.added
                else "- "
                if field.status == FieldStatus.removed
                else "  "
            )
            lines.append(f"  {sym}{field.name}")
        lines.append("")
    return "\n".join(lines)
